### ISSUE TITLE
Metrics buffering shouldn't sum values

### ISSUE THREAD

**Issue by kuteninja** [kontera-technologies/graphite-api#15]
It seems that when I use intervals all the values are summed when sent to graphite, which is not what I want. 

Even, the example is wrong:
```
# Usage:
#     buff = GraphiteAPI::Buffer.new(GraphiteAPI::Utils.default_options)
#     buff << {:metric => {"load_avg" => 10},:time => Time.now}
#     buff << {:metric => {"load_avg" => 30},:time => Time.now}

# Produce:
#    ["load_avg", 40.0, 1326881160]
```

Averages are averages, they are not meant to be summed, the load haven't spiked to 40, it spiked from 10 to 30. 

I'm using simple metrics for a count of total users, and when I add more than 1 point per interval, both values are summed instead of keeping just the last one (which would be ok for me). 

I expected the values to be batched and then sent altogether on a single tcp connection to avoid DoSing the graphite, not to summarize them, however perhaps this is not the way you meant this feature to work.

A simple way to fix this would be to have an enum / string to decide wether to sum, median, average or discard the old repeated points when a new one arrives.

**Comment by Eyal-Shalev** [comment]
Hi @kuteninja, 

We have released a new version (`0.4.0`) of `graphite-api` to support custom aggregations.

With the new version, the default behaviour will remain the same (sum).
But by passing a 3rd parameter (`:sum`, `:avg` or `:replace`) to `client.metric`, the aggregation method for that push will change.

You can also override the client default aggregation method, by passing `:default_aggregation_method => :avg` (or `:replace`) on the client creation.

When using the `graphite-middleware` binary, you can pass the `--aggregation-method` argument to set an aggregation method to be used with it (different aggregation method per push is not supported via `graphite-middleware`).
