### ISSUE TITLE
GraphiteAPI.new needs 100% cpu

### ISSUE THREAD

**Issue by b0e** [kontera-technologies/graphite-api#21]
Hi,

Since version 1.1.0 creating a GraphiteAPI Object consumes a whole virtual cpu constantly. A downgrade to 1.0.0 solves the problem.

Example (the host/port is reachable):
```
client = GraphiteAPI.new( graphite: "tcp://10.10.10.10:2003",  prefix:   "foobar"  )
```

Ruby versions: ruby 2.3.1p112 and  2.6.0 ( I am not aware if other ruby versions are affected.)
OS: Ubuntu 16.04 LTS
Kernel: 4.13.0-32-generic

Kind regards,
b0e

**Comment by Eyal-Shalev** [comment]
@b0e This issue is now fixed (V1.1.1).
Thank you for reporting it.
